name: GloVe word embeddings
website: http://nlp.stanford.edu/projects/glove/
license: Public Domain Dedication and License
tags:
  - word embeddings
papers:
  technical description: http://nlp.stanford.edu/pubs/glove.pdf
description: |
  GloVe is an unsupervised learning algorithm for obtaining vector representations for words.
  Training is performed on aggregated global word-word co-occurrence statistics from a corpus,
  and the resulting representations showcase interesting linear substructures of the word vector space.
data:
  -
    id: 6b
    description: Trained on Wikipedia 2014 + Gigaword 5
    url: http://nlp.stanford.edu/data/glove.6B.zip
    statistics:
      tokens: 6G
      vocabulary: 400K
      cased: false
      dimension: [50, 100, 200, 300]
      size: 822M
  -
    id: 840b
    description: Trained on Common Crawl
    url: http://nlp.stanford.edu/data/glove.42B.300d.zip
    statistics:
    -
      size: 2.03G
      cased: true
      tokens: 840G
      vocabulary: 2.2M
      dimension: 300
  -
    id: 840b
    description: Trained on Common Crawl
    download:
      url: http://nlp.stanford.edu/data/glove.840B.300d.zip
      files: 1
      format: zip
    statistics:
    -
      cased: true
      tokens: 840G
      vocabulary: 2.2M
      dimension: 300
      size: 2.03G
