# Configuration

site_name: Datamaestro
site_description: datamaestro A dataset manager
theme: readthedocs

# Main pages
pages:
  - Home: index.md
  - Configuration: configuration.md
  - Developping: developping.md

# Automatic page generation for datasets
plugins:
  - search
  
# Theme
theme:
    name: material
    feature:
        tabs: true
    palette:
        primary: 'indigo'
        accent: 'indigo'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
