# Configuration

site_name: Datamaestro
site_description: datamaestro A dataset manager
theme: readthedocs
repo_url: https://github.com/bpiwowar/datamaestro

# Main pages
pages:
  - Home: index.md
  - Developping: developping.md
  - API: 
    - Overview: api/index.md
    - Download: api/download.md
    - Data: api/data.md

extra_css: [extra.css]

markdown_extensions: 
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - admonition
  - toc:
      baselevel: 1

# Automatic page generation for datasets
plugins:
  - search
  - datamaestro
  
# Theme
theme:
    name: material
    feature:
        tabs: true
    palette:
        primary: 'indigo'
        accent: 'indigo'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
