# Configuration

site_name: Datamaestro
site_description: datamaestro A dataset manager
theme: readthedocs
repo_url: https://github.com/bpiwowar/datamaestro

# Generate API documentation
generate:
  - api/download.md:
    - datamaestro.download++
    - datamaestro.download.single:
      - datamaestro.download.single.FileDownloader+
    - datamaestro.download.archive++
    - datamaestro.download.links++
  - api/data.md:
    - datamaestro.data++

# Main pages
pages:
  - Home: index.md
  - Developping: developping.md
  - API:
    - Download: api/download.md
    - Data: api/data.md

markdown_extensions: 
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - admonition
  - toc:
      baselevel: 1

# Automatic page generation for datasets
plugins:
  - search
  
# Theme
theme:
    name: material
    feature:
        tabs: true
    palette:
        primary: 'indigo'
        accent: 'indigo'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
