tasks: 
 collections: 
  collection: 
   - 
   _pattern: "trec.*"
    _type: trec
   - 
   document: 
     _pattern: "^AP88.*$"
    _id: "trec.ap88"
    _description: "Associated Press (1988)"
    _path: "cols/ap88.col.files"
   - 
   document: 
     _pattern: "^AP89.*$"
    _id: "trec.ap89"
    _description: "Associated Press (1989)"
    _path: "cols/ap89.col.files"
   - 
   document: 
     _pattern: "^AP90.*$"
    _id: "trec.ap90"
    _description: "Associated Press (1990)"
    _path: "cols/ap90.col.files"
   - 
   _id: "trec.cr1"
   - 
   document: 
     _pattern: "^DOE.*$"
    _id: "trec.doe1"
   - 
   _id: "trec.fbis1"
   - 
   document: 
     _pattern: "^FR88.*$"
    _id: "trec.fr88"
   - 
   _id: "trec.fr89"
   - 
   _id: "trec.fr94"
   - 
   _id: "trec.ft1"
   - 
   _id: "trec.la8990"
   - 
   _id: "trec.sjm1"
   - 
   _id: "trec.usp93"
   - 
   _id: "trec.wsj87"
   - 
   _id: "trec.wsj88"
   - 
   _id: "trec.wsj89"
   - 
   _id: "trec.wsj90"
   - 
   _id: "trec.wsj91"
   - 
   _id: "trec.wsj92"
   - 
   _id: "trec.ziff1"
   - 
   _id: "trec.ziff2"
   - 
   _id: "trec.ziff3"
   - 
   _id: "trec.1.adhoc"
    _ref: "trec.ap88 trec.ap89 trec.doe1 trec.fr88 trec.fr89 trec.wsj87 trec.wsj88 trec.wsj89 trec.wsj90 trec.wsj91 trec.wsj92 trec.ziff1 trec.ziff2"
   - 
   _id: "trec.4.adhoc"
    _ref: "trec.ap88 trec.ap89 trec.ap90 trec.fr88 trec.sjm1 trec.usp93 trec.wsj90 trec.wsj91 trec.wsj92 trec.ziff2 trec.ziff3"
    _path: "cols/trec4.col.files"
   - 
   _id: "trec.5.adhoc"
    _ref: "trec.ap88 trec.cr1 trec.fr88 trec.fr94 trec.ft1 trec.wsj90 trec.wsj91 trec.wsj92 trec.ziff2"
    _path: "cols/trec5.col.files"
   - 
   _id: "trec.6.adhoc"
    _ref: "trec.cr1 trec.fbis1 trec.fr94 trec.ft1 trec.la8990"
   - 
   _id: "trec.7.adhoc"
    _ref: "trec.fbis1 trec.fr94 trec.ft1 trec.la8990"
   - 
   _id: "trec.wt10g"
    _type: "trec.web"
   - 
   _id: "trec.dotgov"
    _type: "trec.web"
   - 
   _id: "trec.dotgov2"
    _type: "trec.web"
   - 
   _id: "trec.aquaint"
    _type: "trec.web"
   - 
   _id: "trec.clueweb09A"
    _type: "warc/0.18"
    _description: "ClueWeb09 Subset A"
   - 
   subcollection: 
     _id: en0000
     "_file-pattern": "en0000-.*"
     "_document-pattern": "en0000/\\d+\\.warc.*"
    _id: "trec.clueweb09b"
    _type: "warc/0.18"
    _description: "ClueWeb09 Subset B"
   - 
   _id: "trec.clueweb12b"
    _type: "warc/0.18"
    _description: "ClueWeb12 Subset B"
    
    
# Topics

 "topics-sets": 
   data: 
     url: "http://trec.nist.gov/data/topics_eng/topics.251-300.gz"
     _type: gz
    _id: "trec.5.adhoc"
    _type: trec
    _path: "trec/trec5/adhoc/trec5.topics.251-300"
   - 
   data: 
     url: "http://trec.nist.gov/data/topics_eng/topics.301-350.gz"
     _type: gz
    _id: "trec.6.adhoc"
    _type: trec
    _path: "trec/trec6/adhoc/trec6.topics.301-350"
   - 
   data: 
     url: "http://trec.nist.gov/data/topics_eng/topics.351-400.gz"
     _type: gz
    _id: "trec.7.adhoc"
    _type: trec
    _path: "trec/trec7/adhoc/trec7.topics.351-400"
   - 
   data: 
     url: "http://trec.nist.gov/data/topics_eng/topics.401-450.gz"
     _type: gz
    property: 
     _name: "comma-separated-phrases"
    _id: "trec.8.adhoc"
    _type: trec
    _path: "trec/trec8/adhoc/trec8.topics.401-450"
   - 
   data: 
     url: "http://trec.nist.gov/data/topics_eng/robust.03.final_100.txt"
    _id: "trec.2003.robust"
    _type: trec
    _path: "trec/2003/robust/topics"
   - 
   data: 
     url: "http://trec.nist.gov/data/robust/04.testset.gz"
     _type: gz
    _id: "trec.2004.robust"
    _type: trec
    _path: "trec/2004/robust/topics"
   - 
   data: 
     url: "http://trec.nist.gov/data/robust/05/05.50.topics.txt"
    _id: "trec.2005.robust"
    _type: trec
   - 
   data: 
     url: "http://trec.nist.gov/data/web/09/wt09.topics.full.xml"
    _id: "ir.trec.2009.web"
    _path: "trec/2009/web/wt09.topics.full.xml"
    _type: "trec.web.2009"
   - 
   data: 
     url: "http://trec.nist.gov/data/web/10/wt2010-topics.xml"
    _id: "ir.trec.2010.web"
    _path: "trec/wt10/web/wt2010-topics.xml"
    _type: "trec.web.2009"
   - 
   data: 
     url: "http://trec.nist.gov/data/web/11/full-topics.xml"
    _id: "ir.trec.2011.web"
    _path: "trec/wt11/web/full-topics.xml"
    _type: "trec.web.2009"
   - 
   data: 
     url: "http://trec.nist.gov/data/web/12/full-topics.xml"
    _id: "ir.trec.2012.web"
    _path: "trec/wt12/web/full-topics.xml"
    _type: "trec.web.2009"
   - 
   data: 
     url: "http://trec.nist.gov/data/web/2013/trec2013-topics.xml"
    _id: "ir.trec.2013.web"
    _path: "trec/web/2013/trec2013-topics.xml"
    _type: "trec.web.2009"
   - 
   data: 
     url: "http://trec.nist.gov/data/web/2014/trec2014-topics.xml"
    _id: "ir.trec.2014.web"
    _path: "trec/web/2014/trec2014-topics.xml"
    _type: "trec.web.2009"


 assessments: 
   -
   data: 
     url: "http://trec.nist.gov/data/qrels_eng/qrels.trec6.adhoc.parts1-5.tar.gz"
     _type: "tar.gz#gz"
    _id: "trec.6.adhoc"
    _path: "trec/trec6/adhoc/qrels.301-350"
    _type: trec
   - 
   data: 
     url: "http://trec.nist.gov/data/qrels_eng/qrels.trec7.adhoc.parts1-5.tar.gz"
     _type: "tar.gz#gz"
    _id: "trec.7.adhoc"
    _path: "trec/trec7/adhoc/qrels.351-400"
    _type: trec
   - 
   data: 
     url: "http://trec.nist.gov/data/qrels_eng/qrels.trec8.adhoc.parts1-5.tar.gz"
     _type: "tar.gz"
    _id: "trec.8.adhoc"
    _path: "trec/trec8/adhoc/qrels.401-450"
    _type: trec
   - 
   data: 
     url: "http://trec.nist.gov/data/robust/qrels.robust2004.txt"
    _id: "trec.2003.robust"
    _type: trec
   - 
   data: 
     url: "http://trec.nist.gov/data/robust/qrels.robust2004.txt"
    _id: "trec.2004.robust"
    _type: trec
   - 
   data: 
     url: "http://trec.nist.gov/data/robust/05/TREC2005.qrels.txt"
    _id: "trec.2005.robust"
    _type: trec
   - 
   data: 
     url: "http://trec.nist.gov/data/web/09/prels.catA.1-50.gz"
     _type: gz
    _id: "trec.2009.web.adhoc.a"
    _path: "trec/2009/web/qrels-1-50-a.dat"
    _type: trec
   - 
   data: 
     url: "http://trec.nist.gov/data/web/09/prels.catB.1-50.gz"
     _type: gz
    _id: "ir.trec.2009.web.adhoc.b"
    _path: "trec/2009/web/qrels-1-50-b.dat"
    _type: trec
   - 
   data: 
     url: "http://trec.nist.gov/data/web/09/qrels.diversity.gz"
     _type: gz
    _id: "ir.trec.2009.web.diversity.b"
    _type: "trec.diversity"
   - 
   data: 
     url: "http://trec.nist.gov/data/web/10/10.adhoc-qrels.final"
    _id: "ir.trec.2010.web.adhoc.b"
    _path: "trec/2010/web/qrels-1-50-b.dat"
    _type: trec
   - 
   data: 
     url: "http://trec.nist.gov/data/web/10/10.diversity-qrels.final"
    _id: "trec.2010.web.diversity"
    _type: "trec.diversity"
   - 
   data: 
     url: "http://trec.nist.gov/data/web/11/qrels.adhoc"
    _id: "ir.trec.2011.web.adhoc.b"
    _path: "trec/web/11/qrels.adhoc"
    _type: trec
   - 
   data: 
     url: "http://trec.nist.gov/data/web/11/qrels.diversity"
    _id: "ir.trec.2011.web.diversity.b"
    _path: "trec/web/11/qrels.diversity"
    _type: trec
   - 
   data: 
     url: "http://trec.nist.gov/data/web/12/qrels.adhoc"
    _id: "ir.trec.2012.web.adhoc.b"
    _path: "trec/web/12/qrels.adhoc"
    _type: trec
   - 
   data: 
     url: "http://trec.nist.gov/data/web/12/qrels.diversity"
    _id: "ir.trec.2012.web.diversity.b"
    _path: "trec/web/12/qrels.diversity"
    _type: trec
   - 
   data: 
     url: "http://trec.nist.gov/data/web/2013/qrels.all.txt"
    _id: "ir.trec.2013.web.adhoc.b"
    _path: "trec/web/2013/qrels.all.txt"
    _type: trec
   - 
   data: 
     url: "http://trec.nist.gov/data/web/2014/qrels.all.txt"
    _id: "ir.trec.2014.web.adhoc.b"
    _path: "trec/web/2014/qrels.all.txt"
    _type: trec



 task: 
   type: TREC
      task: 
       collection: "trec.5.adhoc"
       topics: "trec.5.adhoc"
       qrels: "trec.5.adhoc"
       _description: "Ad-hoc task of TREC 5"
       _name: adhoc
      _abstract: yes
      _name: 1996
     - 
   type: TREC
      task: 
       collection: "trec.6.adhoc"
       topics: "trec.6.adhoc"
       qrels: "trec.6.adhoc"
       _description: "Ad-hoc task of TREC 6"
       _name: adhoc
      _abstract: yes
      _name: 1997
     - 
   type: TREC
      task: 
       collection: "trec.7.adhoc"
       topics: "trec.7.adhoc"
       qrels: "trec.7.adhoc"
       _description: "Ad-hoc task of TREC 7"
       _name: adhoc
      _abstract: yes
      _name: 1998
     - 
   type: TREC
      task: 
       - 
   collection: "trec.7.adhoc"
        topics: "trec.8.adhoc"
        qrels: "trec.8.adhoc"
        _name: adhoc
        _description: "Ad-hoc task of TREC-8"
       - 
   collection: ""
        topics: ""
        qrels: ""
        _name: web
        _description: "Web track of TREC-8 (1999)"
      _name: 1999
      _abstract: yes
     - 
   task: 
       type: TREC
       collection: ft1
       topics: "trec.678.interactive"
       qrels: 
        _type: "trec.aspects"
        _path: "trec/trec678.interactive/trec678.interactive.qrels"
       _name: interactive
      _name: 678
      _abstract: yes
     - 
   type: TREC
      task: 
       collection: wt10g
       topics: "trec.9.web"
       qrels: 
        _type: "trec.adhoc"
        _path: "trec/trec9/web/trec9.web.qrels"
       _name: web
       _description: "Web task TREC-9 (wt10g)"
      _name: 2000
      _abstract: yes
     - 
   type: TREC
      task: 
       collection: wt10g
       topics: "trec.2001.web"
       qrels: 
        _type: "trec.adhoc"
        __text: "trec/trec2001/web/trec2001.web.qrels"
        toString: 
       _name: web
       _description: "Web task TREC 2001 (wt10g)"
      _name: 2001
      _abstract: yes
     - 
   type: TREC
      task: 
       - 
   collection: "trec.7.adhoc"
        topics: "trec.2003.robust"
        qrels: "trec.2003.robust"
        _name: robust
        _description: "Robust task of TREC 2003"
       - 
   collection: "trec.dotgov"
        topics: "trec.2003.web"
        qrels: "trec/trec2003/web/trec2003.web.qrels"
        task: 
         topics: "trec.2003.web.distillation"
         qrels: "trec/trec2003/web/trec2003.web.qrels"
         _name: distillation
         _description: "Web distillation (TREC-2003)"
        _name: web
        _description: "Web task of TREC-2003 (distillation + named page)"
      _name: 2003
      _abstract: yes
     - 
   type: TREC
      task: 
       - 
   collection: "trec.7.adhoc"
        topics: "trec.2004.robust"
        qrels: "trec.2004.robust"
        _name: robust
        _description: "Robust task of TREC 2004"
       - 
   collection: "trec.dotgov"
        topics: "trec.2004.web"
        qrels: "trec/trec2004/web/trec2004.web.qrels"
        _name: web
        _description: "Web task of TREC 2004 (.gov)"
      _name: 2004
      _abstract: yes
     - 
   type: TREC
      task: 
       - 
   collection: "trec.aquaint"
        topics: "trec.2005.robust"
        qrels: "trec.2005.robust"
        _name: robust
        _description: "Robust task of TREC 2005 (Aquaint)"
       - 
   collection: "trec.dotgov"
        topics: "trec.2005.web"
        qrels: "trec/trec2004/web/trec2005.web.qrels"
        _name: web
        _description: "Web task of TREC 2004 (.gov)"
      _name: 2005
      _abstract: yes
     - 
   type: TREC
      task: 
       collection: "trec.dotgov2"
       topics: "trec.2006.terabyte"
       qrels: "trec/trec2006/terabyte/trec2006.terabyte.701-850.qrels"
       _name: terabyte
       _description: "Terabyte task of TREC 2006 (.gov 2)"
      _name: 2006
      _abstract: yes
     - 
   task: 
       task: 
        - 
   type: TREC
         task: 
          collection: "trec.clueweb09b"
          _name: b
          _description: "Web diversity track for TREC 2009 (ClueWeb09B data collection)"
         _name: diversity
         _description: "Web diversity track for TREC 2009"
         _abstract: yes
        - 
   task: 
          collection: "trec.clueweb09b"
          _name: b
          _description: "ClueWeb09B data collection"
         _name: adhoc
         _description: "Web adhoc track"
       _name: web
       _abstract: yes
       _url: "http://plg.uwaterloo.ca/~trecweb/2009.html"
      _name: 2009
      _abstract: yes
      _description: "TREC 2009"
     - 
   type: TREC
      task: 
       - 
   task: 
         collection: "trec.clueweb09b"
         topics: "trec.2010.session"
         _name: b
         _description: "Session track of TREC 2010 using ClueWeb09B"
        _name: session
        _description: "Session track"
        _abstract: yes
        _type: "adhoc session"
       - 
   task: 
         - 
   task: 
           collection: "trec.clueweb09b"
           _name: b
           _description: ClueWeb09B
          _name: adhoc
          _description: "Web adhoc track"
         - 
   type: TREC
          task: 
           _name: b
           _description: ClueWeb09B
          collection: "trec.clueweb09b"
          _name: diversity
          _description: "Web diversity track"
          _type: "adhoc diversity"
          _abstract: yes
        _name: web
        _abstract: yes
        _url: "http://plg.uwaterloo.ca/~trecweb/2010.html"
        _type: adhoc
      _name: 2010
      _abstract: yes
      _description: "TREC 2010"
     - 
   type: TREC
      task: 
       - 
   task: 
         collection: "trec.clueweb09b"
         topics: "trec.2011.session"
         _name: b
         _description: "Session track"
        _name: session
        _description: "Session track"
        _abstract: yes
        _type: "adhoc session"
       - 
   task: 
         - 
   task: 
           collection: "trec.clueweb09b"
           _name: b
           _description: ClueWeb09B
          _name: adhoc
          _description: "Web adhoc track"
         - 
   type: TREC
          task: 
           _name: b
           _description: ClueWeb09B
          collection: "trec.clueweb09b"
          _name: diversity
          _description: "Web diversity track"
          _type: "adhoc diversity"
          _abstract: yes
        _name: web
        _abstract: yes
        _url: "http://plg.uwaterloo.ca/~trecweb/2010.html"
        _type: adhoc
      _name: 2011
      _abstract: yes
      _description: "TREC 2011"
     - 
   type: TREC
      task: 
       - 
   task: 
         collection: "trec.clueweb09b"
         topics: "trec.2011.session"
         _name: b
         _description: "Session track"
        _name: session
        _description: "Session track"
        _abstract: yes
        _type: session
       - 
   task: 
         - 
   task: 
           collection: "trec.clueweb09b"
           _name: b
           _description: ClueWeb09B
          _name: adhoc
          _description: "Web adhoc track"
         - 
   type: TREC
          task: 
           _name: b
           _description: ClueWeb09B
          collection: "trec.clueweb09b"
          _name: diversity
          _description: "Web diversity track"
          _type: "adhoc diversity"
          _abstract: yes
        _name: web
        _abstract: yes
        _url: "http://plg.uwaterloo.ca/~trecweb/2010.html"
        _type: web
      _name: 2011
      _abstract: yes
      _description: "TREC 2011"
      _type: adhoc
     - 
   type: TREC
      task: 
       - 
   task: 
         collection: "trec.clueweb12b"
         topics: "trec.2012.session"
         _name: b
         _description: "Session track"
        _name: session
        _description: "Session track"
        _abstract: yes
        _type: session
       - 
   task: 
         - 
   task: 
           collection: "trec.clueweb12b"
           _name: b
           _description: ClueWeb12B
          _name: adhoc
          _description: "Adhoc track"
         - 
   type: TREC
          task: 
           _name: b
           _description: ClueWeb12B
          collection: "trec.clueweb12b"
          _name: diversity
          _description: "Web diversity track"
          _type: "adhoc diversity"
          _abstract: yes
        _name: web
        _abstract: yes
        _url: "http://plg.uwaterloo.ca/~trecweb/2010.html"
        _type: web
      _name: 2012
      _abstract: yes
      _description: "TREC 2012"
     - 
   type: TREC
      task: 
       - 
   task: 
         collection: "trec.clueweb12b"
         topics: "trec.2013.session"
         _name: b
         _description: "Session track"
        _name: session
        _description: "Session track"
        _abstract: yes
        _type: "adhoc session"
       - 
   task: 
         - 
   task: 
           collection: "trec.clueweb12b"
           _name: b
           _description: ClueWeb12B
          _name: adhoc
          _description: "Web adhoc track"
         - 
   type: TREC
          task: 
           _name: b
           _description: ClueWeb12B
          collection: "trec.clueweb12b"
          _name: diversity
          _description: "Web diversity track"
          _type: "adhoc diversity"
          _abstract: yes
        _name: web
        _abstract: yes
        _url: "http://research.microsoft.com/en-us/projects/trec-web-2013/"
        _type: adhoc
      _name: 2013
      _abstract: yes
      _description: "TREC 2013"
     - 
   type: TREC
      task: 
       - 
   task: 
         collection: "trec.clueweb12b"
         topics: "trec.2014.session"
         _name: b
         _description: "Session track"
        _name: session
        _description: "Session track"
        _abstract: yes
        _type: "adhoc session"
       - 
   task: 
         - 
   task: 
           collection: "trec.clueweb12b"
           _name: b
           _description: ClueWeb12B
          _name: adhoc
          _description: "Web adhoc track"
         - 
   type: TREC
          task: 
           _name: b
           _description: ClueWeb12B
          collection: "trec.clueweb12b"
          _name: diversity
          _description: "Web diversity track"
          _type: "adhoc diversity"
          _abstract: yes
        _name: web
        _abstract: yes
        _url: "http://plg.uwaterloo.ca/~trecweb/2010.html"
        _type: adhoc
      _name: 2014
      _abstract: yes
      _description: "TREC 2014"
    _abstract: yes
    _name: trec
   - 
   type: INEX
    task: 
     collection: "inex.ieee-1.9"
     task: 
      topics: "inex.2005.adhoc.co"
      qrels: "inex/inex2005/adhoc/qrels/official/CO+S"
      _name: co
      _description: "Ad-hoc/content-only task of INEX 2005"
     _abstract: yes
     _name: adhoc
    _abstract: yes
    _name: "inex.2005"
  collections: 
   collection: 
    _id: "inex.ieee-1.9"
    _description: "IEEE (1999-2002) used in INEX 2003-05 "
    __text: "cols/ieee-1.9.col.files"
    toString: 
  "topics-sets": 
   topics: 
    - 
   _id: "inex.2005.adhoc.co"
     _type: directory
     __text: "inex/inex2005/adhoc/topics-v3"
     toString: 
    - 
   _id: "inex.2005.adhoc.cas"
     _type: directory
     __text: "inex/inex2005/adhoc/topics-cas-v3"
     toString: 
  _abstract: yes
  _name: ir
 _xmlns: "net.bpiwowar.irc"