data:
  -
    id: "5"
    description: "TREC 5 topics"
    type: trec/topic
    download:
      url: "http://trec.nist.gov/data/topics_eng/topics.251-300.gz"
      path: "trec/trec5/adhoc/trec5.topics.251-300"
      type: gz

  # -
  #   url: "http://trec.nist.gov/data/topics_eng/topics.301-350.gz"
  #    _type: gz
  #   _id: "trec.6.adhoc"
  #   _type: trec
  #   _path: "trec/trec6/adhoc/trec6.topics.301-350"
  # -
  #   url: "http://trec.nist.gov/data/topics_eng/topics.351-400.gz"
  #    _type: gz
  #   _id: "trec.7.adhoc"
  #   _type: trec
  #   _path: "trec/trec7/adhoc/trec7.topics.351-400"
  # -
  #   url: "http://trec.nist.gov/data/topics_eng/topics.401-450.gz"
  #    _type: gz
  #   property: 
  #    _name: "comma-separated-phrases"
  #   _id: "trec.8.adhoc"
  #   _type: trec
  #   _path: "trec/trec8/adhoc/trec8.topics.401-450"
  # -
  #   url: "http://trec.nist.gov/data/topics_eng/robust.03.final_100.txt"
  #   _id: "trec.2003.robust"
  #   _type: trec
  #   _path: "trec/2003/robust/topics"
  # -
  #   url: "http://trec.nist.gov/data/robust/04.testset.gz"
  #    _type: gz
  #   _id: "trec.2004.robust"
  #   _type: trec
  #   _path: "trec/2004/robust/topics"
  # -
  #   url: "http://trec.nist.gov/data/robust/05/05.50.topics.txt"
  #   _id: "trec.2005.robust"
  #   _type: trec
  # -
  #   url: "http://trec.nist.gov/data/web/09/wt09.topics.full.xml"
  #   _id: "ir.trec.2009.web"
  #   _path: "trec/2009/web/wt09.topics.full.xml"
  #   _type: "trec.web.2009"
  # -
  #   url: "http://trec.nist.gov/data/web/10/wt2010-topics.xml"
  #   _id: "ir.trec.2010.web"
  #   _path: "trec/wt10/web/wt2010-topics.xml"
  #   _type: "trec.web.2009"
  # -
  #   url: "http://trec.nist.gov/data/web/11/full-topics.xml"
  #   _id: "ir.trec.2011.web"
  #   _path: "trec/wt11/web/full-topics.xml"
  #   _type: "trec.web.2009"
  # -
  #   url: "http://trec.nist.gov/data/web/12/full-topics.xml"
  #   _id: "ir.trec.2012.web"
  #   _path: "trec/wt12/web/full-topics.xml"
  #   _type: "trec.web.2009"
  # -
  #   url: "http://trec.nist.gov/data/web/2013/trec2013-topics.xml"
  #   _id: "ir.trec.2013.web"
  #   _path: "trec/web/2013/trec2013-topics.xml"
  #   _type: "trec.web.2009"
  # -
  #   url: "http://trec.nist.gov/data/web/2014/trec2014-topics.xml"
  #   _id: "ir.trec.2014.web"
  #   _path: "trec/web/2014/trec2014-topics.xml"
  #   _type: "trec.web.2009"

  # url: "http://trec.nist.gov/data/topics_eng/topics.251-300.gz"
